// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrGzYlULz5hzIvUTsM0glFHv4Qt_1ciJY',
    appId: '1:132652196683:web:dfbba9f41fc6fabdea3ece',
    messagingSenderId: '132652196683',
    projectId: 'fir-flutter-codelab-24f91',
    authDomain: 'fir-flutter-codelab-24f91.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-24f91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-CQq6bIvb2s3K695vo__audrkvYm-Kvc',
    appId: '1:132652196683:android:3f8e6e894a5ee072ea3ece',
    messagingSenderId: '132652196683',
    projectId: 'fir-flutter-codelab-24f91',
    storageBucket: 'fir-flutter-codelab-24f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Ti-uTZiwQa9qTqO6ZJsWjlkywqWye_M',
    appId: '1:132652196683:ios:c654ae92e48c9e13ea3ece',
    messagingSenderId: '132652196683',
    projectId: 'fir-flutter-codelab-24f91',
    storageBucket: 'fir-flutter-codelab-24f91.appspot.com',
    iosClientId: '132652196683-3484maptuasgctqfv09cf4m5da4tle2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Ti-uTZiwQa9qTqO6ZJsWjlkywqWye_M',
    appId: '1:132652196683:ios:c654ae92e48c9e13ea3ece',
    messagingSenderId: '132652196683',
    projectId: 'fir-flutter-codelab-24f91',
    storageBucket: 'fir-flutter-codelab-24f91.appspot.com',
    iosClientId: '132652196683-3484maptuasgctqfv09cf4m5da4tle2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
